### ISSUE TITLE
SHA.c: loadable library and perl binaries are mismatched

### ISSUE THREAD

**Issue by shawnlaffan** [rschupp/PAR-Packer#10]
I get the error in the subject when there is a second perl in the path which has a different version.  There is no error when there is only one perl in the path.

Tested on Windows using PAR::Packer 1.047 and PAR 1.015 (latest).  

Steps to reproduce are below.  These use portable Strawberry perls managed via [berrybrew](https://github.com/stevieb9/berrybrew), but it also occurs when the second perl is a standard installation.  The same happens with the order of perls reversed.  

I have not been able to track down where it is coming from.

```bat
set PATH=C:\berrybrew\5.26.2_64_PDL\perl\site\bin;C:\berrybrew\5.26.2_64_PDL\perl\bin;C:\berrybrew\5.26.2_64_PDL\c\bin;C:\berrybrew\5.28.0_64_PDL\perl\site\bin;C:\berrybrew\5.28.0_64_PDL\perl\bin;C:\berrybrew\5.28.0_64_PDL\c\bin;%PATH%

pp -e "1"
```

An example result is:
```
SHA.c: loadable library and perl binaries are mismatched (got handshake key 0000000000028fa8, needed 0000000000000000)
```

If I run it multiple times then I get different handshake values, presumably due to different libraries being loaded.  

Thanks,
Shawn.

**Comment by rschupp** [comment]
The error is triggered from function *Perl_xs_handshake* in the Perl source `util.c`. I don't claim to understand the explanation given there and suspect that this a Windows specific problem. 

Note that `pp` runs `par.exe` (extracted from `PAR/StrippedPARL/Dynamic.pm` or maybe `.../Static.pm`) and somewhere down the line `Digest::SHA` is loaded - that's where SHA.c referred to in the error message.

Also: which pp is run in your example?

**Comment by shawnlaffan** [comment]
Thanks Roderich,

pp and perl details for the error in the initial report are below.  

As a further check to see if the build time search for dlls is the root cause, I built PAR::Packer with only the 5.28 perl in the path.  However, the error persists when pp is called with a 5.26 perl later in the path.


Does par.exe search the path to load anything?  If so then maybe it's going to the second instead of the first in the path?  Otherwise I'll see if I can replicate using Digest::SHA.

Regards,
Shawn.


```
pp -V
PAR Packager, version 1.047 (PAR version 1.015)

perl -v

This is perl 5, version 28, subversion 0 (v5.28.0) built for MSWin32-x64-multi-thread
```

**Comment by shawnlaffan** [comment]
Just an update, the error needs the second perl's bin directory to be in the path.  The c/bin and site/bin directories have no effect.

Something is looking in the wrong perl/bin dir.

(This also corrects the path order from the original report - it should have been 5.28 and then 5.26, although the error occurs for either case).  

```
set PATH=C:\berrybrew\5.28.0_64_PDL\c\bin;C:\berrybrew\5.28.0_64_PDL\perl\site\bin;C:\berrybrew\5.28.0_64_PDL\perl\bin;C:\berrybrew\5.26.11_64_PDL\perl\bin;%PATH%
```

**Comment by rschupp** [comment]
It may be relevant that you're using *portable* Strawberry perl installations. I think they are built with the *relocatable* option, i.e. any member of @INC that starts with ".../" has this prefix replaced with the `dirname` of the executable. And `par` (extracted to some temp file) inherits this behaviour.

**Comment by shawnlaffan** [comment]
It's looking likely that something in portable Strawberry perl is the root cause.  The error does not occur when the first perl in the path is a standard installation but the second is portable.  (Tested using PAR::Packer 1.045 and 1.047).  

I'm not sure where it is picking up the wrong path name from, though.  Dumping ```%Config::Config``` for a portable perl 5.28 first in the path shows nothing that refers to the 5.26 path.  Neither does ```perl -V```.

**Comment by rschupp** [comment]
If you copy a portable perl.exe to, e.g. `%TMP%/foo.exe`, what does running `foo.exe -V` report about `@\INC`?

**Comment by shawnlaffan** [comment]
I copied two versions across, foo5.28.0.exe and foo5.26.2.exe.  

The ```@INC``` entries are picking up the first matching install of strawberry perl.  This is regardless of what else is in the path.  

However, ldflags, lddflags and libpth all point to C:\strawberry.  C:\strawberry is not in the path when I run these calls.

```
ldflags ='-s -L"C:\strawberry\perl\lib\CORE" -L"C:\strawberry\c\lib"'
lddlflags='-mdll -s -L"C:\strawberry\perl\lib\CORE" -L"C:\strawberry\c\lib"'
libpth=C:\strawberry\c\lib C:\strawberry\c\x86_64-w64-mingw32\lib C:\strawberry\c\lib\gcc\x86_64-w64-mingw32\7.1.0
```

The libperl entry is version specific: ```libperl=libperl528.a``` or ```libperl=libperl526.a```.

Let me know if you want full ```perl -V``` dumps.  

As a further point, C:\strawberry\perl is version 5.26.1, so one minor version earlier than the 5.26.2 I have been testing with.  Copying it to %TMP%\foos5.26.1.exe gives the same results for ```perl -V```, but this minor version difference might be related to the handshake error.

**Comment by rschupp** [comment]
Looking at ldflags, lddflags and libpth above I suspect that the problem is caused by a faulty build of PAR::Packer. 

Can you rename `C:\Strawberryx` back to `C:\Strawberry` and attach the full log of building PAR::Packer with one of the portable installations.

**Comment by shawnlaffan** [comment]
There is no meaningful difference in the build log when C:\Strawberry is renamed to c:\Strawberryx.  

All that changes is the order of file copies and embedding operations.

**Comment by rschupp** [comment]
Yeah, the build log looks OK - no contamination with the stuff in `C:\Strawberry`

**Comment by shawnlaffan** [comment]
Given the foo.exe results, is there something in the packing sequence where a foo.exe equivalent loses track of the perl it is from and points to C:\strawberry?

**Comment by rschupp** [comment]
Yes, though I dunno how. The  `require Digest::SHA` on line 605 of `script/par.pl` executed by `par.exe` (build from the portable installation) sometimes is called with

```perl
@INC = qw( C:\strawberry\perl\lib C:\strawberry\perl\lib C:\strawberry\perl\site\lib C:\strawberry\perl\site\lib C:\strawberry\perl\vendor\lib C:\strawberry\perl\vendor\lib )
```
Adding `Digest::SHA` to the list in `require_modules()` makes this module available in the cache area and hence works around this problem.

Shawn, can you try with HEAD from Git (you'll have to rebuild PAR::Packer for your portbale installations)?

**Comment by shawnlaffan** [comment]
Thanks Roderich, that works on my system.
