### ISSUE TITLE
1.048 not compiled on linux

### ISSUE THREAD

**Issue by zdm** [rschupp/PAR-Packer#15]
```
"/usr/perlbrew/perls/perl-5.28.2/bin/perl" -Mblib=.. run_with_inc.pl ./par -q -B -Oparldyn
Can't locate Digest/SHA.pm in @INC (you may need to install the Digest::SHA module) (@INC contains: /mnt/hgfs/projects/pcore-lib/pcore/lib /tmp/.cpanm/work/1556682277.52386/PAR-Packer-1.048/lib/site_perl/5.28.2/x86_64-linux-ld /tmp/.cpanm/work/1556682277.52386/PAR-Packer-1.048/lib/site_perl/5.28.2 /tmp/.cpanm/work/1556682277.52386/PAR-Packer-1.048/lib/5.28.2/x86_64-linux-ld /tmp/.cpanm/work/1556682277.52386/PAR-Packer-1.048/lib/5.28.2 .) at -e line 474.
system(./par -I../blib/arch -I../blib/lib -I/mnt/hgfs/projects/pcore-lib/pcore/lib -I/usr/perlbrew/perls/perl-5.28.2/lib/site_perl/5.28.2/x86_64-linux-ld -I/usr/perlbrew/perls/perl-5.28.2/lib/site_perl/5.28.2 -I/usr/perlbrew/perls/perl-5.28.2/lib/5.28.2/x86_64-linux-ld -I/usr/perlbrew/perls/perl-5.28.2/lib/5.28.2 -I. -q -B -Oparldyn) failed:
make[1]: *** [Makefile:908: parldyn] Error 2
make[1]: Leaving directory '/tmp/.cpanm/work/1556682277.52386/PAR-Packer-1.048/myldr'
make: *** [Makefile:542: subdirs] Error 2
FAIL
! Installing R/RS/RSCHUPP/PAR-Packer-1.048.tar.gz failed. See /tmp/.cpanm/work/1556682277.52386/build.log for details. Retry with --force to force install it.
```
Seems, that it removes perl locations from @INC.

**Comment by rschupp** [comment]
I can't reproduce that (and CPAN Testers can't either)

**Comment by zdm** [comment]
Hi, could you, please, do something or revert latest changes?
It is simply not installed.

**Comment by rschupp** [comment]
There's almost no information in your issue to start diagnosing the problem.

- Where did `/usr/perlbrew/perls/perl-5.28.2` come from? 

- Please show the output of `/usr/perlbrew/perls/perl-5.28.2 -V`

- Please run `cpanm -v PAR::Packer` (in this Perlbrew environment) and attach the **complete** output.

**Comment by zdm** [comment]
hi, please, look at attached logs.
[1.txt](https://github.com/rschupp/PAR-Packer/files/3185119/1.txt)
[2.txt](https://github.com/rschupp/PAR-Packer/files/3185120/2.txt)

**Comment by rschupp** [comment]
Here's the problem:

config_args='-des -Dusemorebits -Duselargefiles -Dprefix=/usr/perlbrew/perls/perl-5.28.2 **-Dusere locatableinc** -Dman1dir=none -Dman3dir=none'

i.e. `/usr/perlbrew/perls/perl-5.28.2` is a "relocatable" Perl interpreter: if it's installed into directory
`foo` it's default `@INC` will  be `../foo/lib/5.28.2`, `../lib/site_perl/5.28.2` etc
That makes `myldr/par` a relocatable Perl interpreter, too (and you can recognize that from the `@INC` shown in the error message). 

This has come up before with "portable" editions of [Strawberry Perl](http://strawberryperl.com/releases.html).  IIRC my conclusion then was that `require Digest::SHA`  didn't work there, too, but previously that was hidden as it was inside `eval { ... }'. 
I'll do some experiments...

**Comment by zdm** [comment]
Thank you.

**Comment by rschupp** [comment]
Can you try current HEAD?

**Comment by zdm** [comment]
Current HEAD compiled without errors.

**Comment by rschupp** [comment]
Thx for testing
