### ISSUE TITLE
Subroutine redefined warnings

### ISSUE THREAD

**Issue by marghidanu** [rschupp/PAR-Packer#25]
Is there a way to suppress these types of messages?

`Subroutine DESTROY redefined at /usr/local/share/perl5/site_perl/Mojo/IOLoop/Client.pm line 25`

These are polluting the output of `pp`

**Comment by rschupp** [comment]
@marghidanu Please give a simple example (script and `pp` command) so that I can reproduce your problem.

**Comment by marghidanu** [comment]
Sure thing, here's exactly what I use for my application:

```
 pp ./scripts/app.pl 
        --output app 
        --compile 
        --lib lib 
        --module "Whatever::" 
        --module "MooseX::Log::Log4perl::" 
        --module "MooseX::Storage::"
        --module "Mojo::"
        --module "Mojolicious::Plugin::"
        --addfile "/usr/local/share/perl5/site_perl/Mojo/resources/;lib/Mojo/resources/"
        --addfile "/usr/local/share/perl5/site_perl/Mojo/IOLoop/resources/;lib/Mojo/IOLoop/resources/"
        --addfile "/usr/local/share/perl5/site_perl/Mojolicious/resources/;lib/Mojolicious/resources/"
```

In this case, Mojolicious is the culprit.

**Comment by rschupp** [comment]
It's a strange interaction between options "--compile" and "--module Foo::"

@marghidanu You got have saved me some time by posting your `pp` recipe and the complete output of `pp` in the initial issue (w/o me having to explicitly ask for it). Can you retry with PAR::packer master?

**Comment by marghidanu** [comment]
If you need additional information for your bugfixes create an issue template explaining what you require or have a section in your readme.

**Comment by marghidanu** [comment]
The output is ok now.
