### ISSUE TITLE
Perl 5.32 utf8_heavy.pl error running pp with "--unicode"

### ISSUE THREAD

**Issue by plk** [rschupp/PAR-Packer#29]
It seems that perl 5.32, at least on Strawberry 32 and 64 bit and linux 64-bit doesnt' include `utf8_heavy.pl` any more for some reason and this makes `pp --unicode` die. I thought initially it was some packaging error with Strawberry but I had the same with a fresh 5.32 build on linux 64-bit. I had to copy the `utf8_heavy.pl` from a 5.30 install and then it was fine ... not sure if you are aware of this.

**Comment by rschupp** [comment]
See #27 and 911c644d550f7ebb54a9c5097238e2e94c37f033. I'll put out a release in a few hours.
