### ISSUE TITLE
My pp generated app doubles itself and it's children when run - why?

### ISSUE THREAD

**Issue by PesoMemo** [rschupp/PAR-Packer#43]
I created a Tk GUI app using AS Perl v5.20.2 with pp.pm v 0.992 on Windows 10 .

The GUI does a Win32::Process::Create to basically fork off a task to do URL fetches asynchronously (so as not to lock up the GUI part).
After building with pp, everything runs ok (w or w/o --gui switch), but I get 2 copies of the GUI and 2 copies of the forked off async app showing up in Task Manager.
When I kill the forked off async task from the GUI task and exit the GUI task, both of the GUI processes exit OK, but only one of the async processes gets killed.  This leaves me with multiple async tasks floating around - one per run.
1) Why are the processes doubled?
2) Why does the second async task not die?

**Comment by rschupp** [comment]
Are you sure that you really see 2 copies of the GUI process? This is how  a `pp` packed executable `foo.exe` works on Windows:
- the original `foo.exe` creates a cache directory and extracts some stuff into it (if that doesn't exist already)
- among the stuff is a custom perl interpreter which is also called `foo.exe` (in the cache directory)
- it then spawns this custom interpreter which will run your original script (and waits for it to exit)
So it is expected that you see 2 processes named `foo.exe`.

What is the actual call to `Win32::Process::Create`?

**Comment by rschupp** [comment]
> $pcExe = 'D:/tmp/Pub/GetFileUI.exe'

I guess this is another `pp`-packed executable? This would explain what you're seeing - instead of killing the "real" async process you're killing its "boot" process (note that the "boot" process doesn't handle any signals, esp. it will **not** kill its child).

Why not use `fork` instead of `Win32::Process::Create`? Or look into the `--reusable` option of `pp`?

**Comment by PesoMemo** [comment]
Yes, they're both pp generated.
I'll look into those two options and get back to you.
