### ISSUE TITLE
[FEATURE REQUEST] Code Signing?

### ISSUE THREAD

**Issue by LeeThompson** [rschupp/PAR-Packer#46]
I'm sure this is impossible but it would be awesome if the compiled product could have a code signature added.

**Comment by rschupp** [comment]
> I'm sure this is impossible but it would be awesome if the compiled product could have a code signature added.

It's possible and has apparently been done at least on MacOS, search for "signing" on archives of the `par@perl.org` mailing list, e.g. https://www.mail-archive.com/par@perl.org/ 
However, the signing process itself is definitely not a goal for `PAR::Packer`, only removing technical hurdles or adding a few lines of documentation (as was the case for MacOS).

**Comment by fantinuoli** [comment]
Yes, it is possible and easy to do. You can codesign it as a part of an .app bundle, or codesign it directly. To codesign is as part of an .app bundle:

- Download the utility available in this repository contrib/pp_osx_codesign_fix
- Generate the executable your usual way
- Fix executable for code signing by running the downloaded utility
- Codesign the .app bundle with patched executable. From command line: $ codesign --deep --options runtime --timestamp -s "Developer ID A" /<PATH>/myApp.app  (where "Developer ID A" is your certificate)
