### ISSUE TITLE
PAR should provide empty `caller()` to the script

### ISSUE THREAD

**Issue by mik2** [rschupp/PAR-Packer#51]
It is a common trick to use a module also as a script by checking `caller()` to be false in scalar context. Such a script when packaged with PAR will behave as a module because `caller()` will return `PAR`, which is different from running the script without packaging. A workaround is to test `caller()` to be empty or `PAR`, but this requires modification of the original script. A method used in `Call::From` could be used to fake the script as being run in top level (so that `caller()` returns an empty string).

**Comment by rschupp** [comment]
> It is a common trick to use a module also as a script by checking caller() to be false in scalar context. Such a script when packaged with PAR will behave as a module because caller() will return PAR, which is different from running the script without packaging. 

Don't do that then. Just pack a oneliner instead of the original script-or-module.
