### ISSUE TITLE
CryptFile.so: undefined symbol: OPENSSL_init_crypto

### ISSUE THREAD

**Issue by leandrocombr** [rschupp/PAR-Packer#52]
Hello i'm running the command

pp -f Crypto -M Filter::Crypto::Decrypt -o hello hellp.pl

And I get the following message. I couldn't resolve it.

/usr/bin/perl: symbol lookup error: /usr/lib/perl5/site_perl/5.34.0/x86_64-linux/auto/Filter/Crypto/CryptFile/CryptFile.so: undefined symbol: OPENSSL_init_crypto

**Comment by rschupp** [comment]
I can't reproduce this. What does 
```
readelf -d /usr/lib/perl5/site_perl/5.34.0/x86_64-linux/auto/Filter/Crypto/CryptFile/CryptFile.so
```
print?

**Comment by leandrocombr** [comment]
[root@servidor]# readelf -d /usr/lib/perl5/site_perl/5.34.0/x86_64-linux/auto/Filter/Crypto/CryptFile/CryptFile.so

readelf: /usr/lib/perl5/site_perl/5.34.0/x86_64-linux/auto/Filter/Crypto/CryptFile/CryptFile.so: Error: No such file

**Comment by leandrocombr** [comment]
Thanks.

I installed CryptFile.so and it worked perfectly.

I need to protect source code or make access to PERL source code difficult.

Any suggestion?
