### ISSUE TITLE
./test: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./test)

### ISSUE THREAD

**Issue by 825644691** [rschupp/PAR-Packer#59]
pp --link=/usr/lib64/libc-2.17.so -o test test.pl

I make in centos7 and execute in centos6.....how to compile the glibc into the executable file?
./test: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./test)

**Comment by rschupp** [comment]
> how to compile the glibc into the executable file?

You can't, sorry.

**Comment by 825644691** [comment]
> > how to compile the glibc into the executable file?
> 
> You can't, sorry.

has any way to make in centos7 and execute in centos6.

**Comment by 825644691** [comment]
I just want to compile the excutable file running in centos6(glibc2.12) and centos7(glibc2.17),has any way?
