### ISSUE TITLE
different libraries

### ISSUE THREAD

**Issue by EnzoRossi1954** [rschupp/PAR-Packer#61]
I generated an executable on fedora:
Fedora release 35 (Thirty Five)
NAME = "Fedora Linux"
VERSION = "35 (Workstation Edition)"
I ran the executable on Debian 11 and the result is:
./EPVzParserAgentsHandler: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33 'not found (required by ./EPVzParserAgentsHandler)
./EPVzParserAgentsHandler: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34 'not found (required by ./EPVzParserAgentsHandler)
while everything is running fine on Fedora, how can this problem be avoided?

**Comment by rschupp** [comment]
That's the same problem encountered in #60: Fedora 35 uses glibc 2.34 while Debian 11 is at glibc 2.31.
You must generate your executable on the platform with the **oldest** version of glibc.
