### ISSUE TITLE
Can't load '%TMP%\par-6a6f6b\cache-1234567890abcdef\123456789.xs.dll' for module X::Y::Z

### ISSUE THREAD

**Issue by hoppfrosch** [rschupp/PAR-Packer#75]
Hi there,

I compiled a quite complex Perl Script via pp.bat on a reference machine.
Running the produced exe on a few different computers was successfull - whilst on most other computers execution of compiled exe failed due to an error

The error message during execution is as follows:

```
Can't load 'C:\Users\XXX\AppData\Local\Temp\par-6a6f6b\cache-796f45c9f359ff639862f1260cfe0060cbe429a0\1dfc9682.xs.dll' for module XML::Parser::Expat: load_file:The specified module could not be found at <embedded>/DynaLoader.pm line 193.
  at <embedded>/PAR/Heavy.pm line 140.
Compilation failed in require at C:\Users\xxx\AppData\Local\Temp\par-6a6f6b\cache-796f45c9f359ff639862f1260cfe0060cbe429a0\inc\lib/XML/Parser.pm line 18.
BEGIN failed--compilation aborted at C:\Users\xxx\AppData\Local\Temp\par-6a6f6b\cache-796f45c9f359ff639862f1260cfe0060cbe429a0\inc\lib/XML/Parser.pm line 22.
Compilation failed in require at C:\Users\xxx\AppData\Local\Temp\par-6a6f6b\cache-796f45c9f359ff639862f1260cfe0060cbe429a0\inc\lib/XML/Twig.pm line 151.
BEGIN failed--compilation aborted at C:\Users\xxx\AppData\Local\Temp\par-6a6f6b\cache-796f45c9f359ff639862f1260cfe0060cbe429a0\inc\lib/XML/Twig.pm line 151.
Compilation failed in require at C:\Users\xxx\AppData\Local\Temp\par-6a6f6b\cache-796f45c9f359ff639862f1260cfe0060cbe429a0\inc\lib/ABC/DEF.pm line 63.
BEGIN failed--compilation aborted at C:\Users\xxx\AppData\Local\Temp\par-6a6f6b\cache-796f45c9f359ff639862f1260cfe0060cbe429a0\inc\lib/ABC/DEFc.pm line 63.
Compilation failed in require at script/ABC.pl line 181.
BEGIN failed--compilation aborted at script/ABC.pl line 181.
```

The reference machine - where compilation took place - has following parameters:

- OS: MS Win10 Enterprise 10.0.19045 64bit
- Perl: Strawberry-Perl 5.26.0.1 (for some reasons I have to keep stucked on this version)
- PAR: 1.018 - PAR::Dist: 0.52 - PAR::Packer: 1.059 (first compiled with older versions of PAR ... but with same errors)

I used the following command line to compile:
`pp.bat --execute --lib=..\lib --output=ABC.exe --xargs="-c TmpConfig.xml" ABC.pl`

The resulting ABC.exe has a size of approx 15MB.

Running ABC.exe on several windows machines (different OS Versions, some with local Perl installed, some not ...) leads to different results. Whilst execution on a few machines succeeds, exection failed on an most machines due to error above.

**What I analyzed/tried yet:** 
* I took a look into the generated %TMP%/par-xxxxx folder - having an special eye on *.xs.dll files in %TMP%/par-xxx/cache-yyyy/inc/lib/* and in %TMP%/par-xxx/cache-yyyy
  * On "successful" machines there have been 
		* 67 *.xs.dll files under par-xxx/cache-yyyy/inc/lib/* 
		* 33 *.xs.dll files under par-xxx/cache-yyyy/inc/lib/* 
		* 1dfc9682.xs.dll (mentioned in the error message above) exists
  * On "erroneous machines" there have been
		* 67 *.xs.dll files under par-xxx/cache-yyyy/inc/lib/*
		* 13 *.xs.dll files under par-xxx/cache-yyyy/inc/lib/*  - quite a few are missing in comparison to "successful machines"
		* 1dfc9682.xs.dll (mentioned in the error message above) exists - but the above error occurs nonetheless
* On "erroneous machones" I replaced the PAR-Folder with the one from "successfull machines" - without any success. The error still occurs.

I found no sytematics to distinguish the erroneous machines from succcessful machines.

**Comment by rschupp** [comment]
> Can't load 'C:\Users\XXX\AppData\Local\Temp\par-6a6f6b\cache-796f45c9f359ff639862f1260cfe0060cbe429a0\1dfc9682.xs.dll' for module XML::Parser::Expat: load_file:The specified module could not be found at <embedded>/DynaLoader.pm line 193.
  at <embedded>/PAR/Heavy.pm line 140.

The problem is most likely that module `XML::Parser::Expat` has an XS part (i.e. .../XML/Parser/Expat/Expat.xs.dll) that is linked against the "real" expat DLL, e.g. libexpat*.dll. To confirm, run `objdump -ax` on the dll from the "Can't load" error message and look for "DLL Name: ...." lines in the output. 
libexpat*.dll comes with Strawberry, but `PAR::Packer` does **not** pack it automagically (see https://github.com/rschupp/PAR-Packer/issues/67#issuecomment-1249196382 for a more elaborate explanation), hence the packed executable will work on machines that have Strawberry installed (or have libexpat*.dll in their `PATH` from some other distribution) and fail on others. 
To fix, either add libexpat*.dll manually (with `pp --link ...`) or use Shawn Laffan's [APP::PP::Autolink](https://metacpan.org/pod/App::PP::Autolink).

**Comment by hoppfrosch** [comment]
Following your recommendation, I used Shawn Laffan's [APP::PP::Autolink](https://metacpan.org/pod/App::PP::Autolink) to compile/pack my PerlScript. 
The newly compiled exe significantly grows in size in comparison to the erroneous one. Looking inside the exe, libexpat*.dll was available - as you predicted correctly (libexpat*.dll was not available in the erroneous version).

Running the new exe on different machines work without any flaws ....

Thanky you so much for your fast and helpful answer! You are my hero of the day ;-)
