### ISSUE TITLE
Mojo app full

### ISSUE THREAD

**Issue by leandrocombr** [rschupp/PAR-Packer#77]
Can I create a PAR::Packer from a mojo app full?

And how to merge all the files

**Comment by rschupp** [comment]
> Can I create a PAR::Packer from a mojo app full?

Maybe. Expect to run into lots of problems,  esp. with Mojo's resource files as `PAR::Packer` has absolutely no provisions to recognize, locate and pack them. People have tried to do this, e.g. [PerlMonks](https://perlmonks.org). You may want to search for "mojo packer" there, but discard any posts before 2019 and newer advice seems outdated or dubious. Note that any problems wrt `__FILE__` have been fixed. You may also post this question on the mailing list `par@perl.org` (no subscription required), but it is mostly dormant these days.

Please note that this GitHub issue tracker is for concrete bugs and not a general help forum.
