### ISSUE TITLE
Setting tmp folder

### ISSUE THREAD

**Issue by fantinuoli** [rschupp/PAR-Packer#81]
pp sets automatically the tmp folder in which to unpack the application. On macOS this is typically: 

`% echo $TMPDIR`

The issue is that this folder will be cleared after a reboot. Since apps can be heavy, start time will be very slow after each reboot. Is it possible to force another location to unpack the application? Something like:

`% echo $HOME`

**Comment by rschupp** [comment]
> Is it possible to force another location to unpack the application? 

Set the environment variable `PAR_GLOBAL_TMPDIR`, cf.  https://metacpan.org/pod/PAR#NOTES 
Note that this directory may grow over time as every "updated" version of a packed ececutable will be extracted to a different subdirectory and outdated ones are not purged.
