### ISSUE TITLE
Adding visual message during enzipping exe

### ISSUE THREAD

**Issue by TakamotoAI** [rschupp/PAR-Packer#83]
Hello,

unzipping the content of exe can take a long time, and the user is left without any info about why nothing is happening after double clicking the app icon. Is it possible to show a message to the user before or during the unzipping process? I thin there is nothing build in, so I would like to have some info about where to look into if I want to add this behavior to the created app. Thanks.

**Comment by rschupp** [comment]
> Is it possible to show a message to the user before or during the unzipping process?

Nope
