### ISSUE TITLE
PAR::Packer packaged scripts lose the ability to parse UTF-8 arguments from the command line

### ISSUE THREAD

**Issue by fengzyf** [rschupp/PAR-Packer#84]
The answer provided in ["Handling wide char values returned by Win32::API"](https://stackoverflow.com/questions/44488898/handling-wide-char-values-returned-by-win32api/44489228#44489228) can parse UTF-8 command line arguments on windows. 

But with Par Packer packaging, the parsing failed.

If I save this code

```
use strict;
use warnings;
use feature qw( say state );

use open ':std', ':encoding('.do { require Win32; "cp".Win32::GetConsoleOutputCP() }.')';

use Config     qw( %Config );
use Encode     qw( decode encode );
use Win32::API qw( ReadMemory );

use constant PTR_SIZE => $Config{ptrsize};

use constant PTR_PACK_FORMAT =>
     PTR_SIZE == 8 ? 'Q'
   : PTR_SIZE == 4 ? 'L'
   : die("Unrecognized ptrsize\n");

use constant PTR_WIN32API_TYPE =>
     PTR_SIZE == 8 ? 'Q'
   : PTR_SIZE == 4 ? 'N'
   : die("Unrecognized ptrsize\n");

    
sub lstrlenW {
   my ($ptr) = @_;

   state $lstrlenW = Win32::API->new('kernel32', 'lstrlenW', PTR_WIN32API_TYPE, 'i')
      or die($^E);

   return $lstrlenW->Call($ptr);
}


sub decode_LPCWSTR {
   my ($ptr) = @_;
   return undef if !$ptr;

   my $num_chars = lstrlenW($ptr)
      or return '';

   return decode('UTF-16le', ReadMemory($ptr, $num_chars * 2));
}


# Returns true on success. Returns false and sets $^E on error.
sub LocalFree {
   my ($ptr) = @_;

   state $LocalFree = Win32::API->new('kernel32', 'LocalFree', PTR_WIN32API_TYPE, PTR_WIN32API_TYPE)
      or die($^E);

   return $LocalFree->Call($ptr) == 0;
}


sub GetCommandLine {
   state $GetCommandLine = Win32::API->new('kernel32', 'GetCommandLineW', '', PTR_WIN32API_TYPE)
      or die($^E);

   return decode_LPCWSTR($GetCommandLine->Call());
}


# Returns a reference to an array on success. Returns undef and sets $^E on error.
sub CommandLineToArgv {
   my ($cmd_line) = @_;

   state $CommandLineToArgv = Win32::API->new('shell32', 'CommandLineToArgvW', 'PP', PTR_WIN32API_TYPE)
      or die($^E);

   my $cmd_line_encoded = encode('UTF-16le', $cmd_line."\0");
   my $num_args_buf = pack('i', 0);  # Allocate space for an "int".

   my $arg_ptrs_ptr = $CommandLineToArgv->Call($cmd_line_encoded, $num_args_buf)
      or return undef;

   my $num_args = unpack('i', $num_args_buf);
   my @args =
      map { decode_LPCWSTR($_) }
         unpack PTR_PACK_FORMAT.'*',
            ReadMemory($arg_ptrs_ptr, PTR_SIZE * $num_args);

   LocalFree($arg_ptrs_ptr);
   return \@args;
}


{
   my $cmd_line = GetCommandLine();

   say $cmd_line;

   my $args = CommandLineToArgv($cmd_line)
      or die("CommandLineToArgv: $^E\n");

   for my $arg (@$args) {
      say "<$arg>";
   }
}
```
in CmdArgs.pl and run `perl CmdArgs.pl äö.txt`, the cmd window displays

```
perl  CmdArgs.pl äö.txt
<perl>
<CmdArgs.pl>
<äö.txt>
```
I then packaged the CmdArgs.pl with the Par Packer command `pp -o CmdArgs.exe CmdArgs.pl`,
When I run `CmdArgs.exe äö.txt`, the cmd window shows

```
C:\Users\lenovo\AppData\Local\Temp\par-5875\cache-622ad9aefc40f2ce41f40707644eb592d3c73c6a/CmdArgs.exe ??.txt
<C:\Users\lenovo\AppData\Local\Temp\par-5875\cache-622ad9aefc40f2ce41f40707644eb592d3c73c6a/CmdArgs.exe>
<??.txt>
```
What I want it to show is

```
C:\Users\lenovo\AppData\Local\Temp\par-5875\cache-622ad9aefc40f2ce41f40707644eb592d3c73c6a/CmdArgs.exe äö.txt
<C:\Users\lenovo\AppData\Local\Temp\par-5875\cache-622ad9aefc40f2ce41f40707644eb592d3c73c6a/CmdArgs.exe>
<äö.txt>
```

Info:

* Win11
* The OS language is simplified Chinese
* The values of `ACP`, `OEMCP` and `MACCP` in the registry `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage` are 936, 936, and 10008.
* I use `chcp 65001` in `cmd` to change the console's CP. 

Debugging:

* `Win32::GetConsoleOutputCP()` returns 65001 (UTF-8) as expected.
* `$args->[ $#$args ]` is `3F.3F.2E.74.78.74` (as returned by `sprintf "%vX"`).
* `$cmd_line` is `….2F.43.6D.64.41.72.67.73.2E.65.78.65.20.3F.3F.2E.74.78.74`.
* The memory returned by `GetCommandLineW` is `….2F.0.43.0.6D.0.64.0.41.0.72.0.67.0.73.0.2E.0.65.0.78.0.65.0.20.0.3F.0.3F.0.2E.0.74.0.78.0.74.0`.

I also asked on stackoverflow see (https://stackoverflow.com/questions/77880391/parpacker-packaged-scripts-lose-the-ability-to-parse-utf-8-arguments-from-the), but it looks like the problem was caused by a PAR-Packer.

**Comment by rschupp** [comment]
> I also asked on stackoverflow see (https://stackoverflow.com/questions/77880391/parpacker-packaged-scripts-lose-the-ability-to-parse-utf-8-arguments-from-the), but it looks like the problem was caused by a PAR-Packer.

You didn't read carefully: ikegami wrote "**Works for me**".

I can't test this anyway (no Windows here), but I'm curious: what is the actual problem you're trying to solve?
Why do you need `GetCommandLineW`, what's wrong with `@ARGV`?

**Comment by rschupp** [comment]
> I guess the reason for the occurrence is:
When I run CmdArgs.exe äö.txt, CmdArgs.exe automatically decompresses to a temporary directory, recording the new execution file path as $path_new and the command line parameter @args_new (which also only supports characters in ACP (936), "äö" has been replaced by "??"), and then runs a new command based on $path_new and @args_new. Therefore, the command line parameter obtained by GetCommandLineW is C:\Users\lenovo\AppData\Local\Temp\par-5875\cache-622ad9aefc40f2ce41f40707644eb592d3c73c6a/CmdArgs.exe ??.txt.

That's basically correct. A few more details:
- your CmdArgs.exe is (at least when only looking at the control flow) implemented in `myldr/boot.c`
- it get's its command line via C/POSIX standard
```
int main ( int argc, char **argv, char **env )
```
- whatever the "standard C library" on Windows does, it most likely uses `GetCommandLineA` to fill in `argv` ☹️ 
- it creates the cache directory `C:\Users\lenovo\AppData\Local\Temp\par-5875\cache-622ad9aefc40f2ce41f40707644eb592d3c73c6a` if necessary and extracts (amongst others) a file called `CmdArgs.exe` into it which is a special purpose perl interpreter; the path to this perl interpreter is called `my_perl` in `myldr/boot.c` 
- it then executes it with (`argv` is passed unchanged)
```
rc = spawnvp(P_WAIT, my_perl, (char* const*)argv);
```
- the source for the interpreter is in `myldr/main.c`
- it get's its command line as above and augments `argv` with a few additional arguments resulting in `fakeargv`
- finally it starts the actual perl machinery with
```
exitstatus = perl_parse(my_perl, par_xs_init, fakeargc, fakeargv, NULL);
```

Note: The problem with command line handling for Perl on Windows is known, e.g. [@ARGV, -CA and Win32](https://github.com/Perl/perl5/issues/16681), but no solution so far.

**Comment by rschupp** [comment]
I committed a slightly edited version of your patch to branch "ci".
Can you test  with that?

**Comment by rschupp** [comment]
> The content of E:\argv.txt is as follows:

OK, as expected. Now let's see what the custom perl interpreter sees (before perl gets to work).
Please apply the folowing patch to  `myldr/main.c`
```
diff --git a/myldr/main.c b/myldr/main.c
index ffb8790..d0cb1b5 100644
--- a/myldr/main.c
+++ b/myldr/main.c
@@ -99,6 +99,18 @@ int main ( int argc, char **argv, char **env )
     PL_exit_flags |= PERL_EXIT_EXPECTED;
 #endif /* PERL_EXIT_EXPECTED */
 
+    {
+        int i;
+        unsigned char *p;
+        printf("main.c argv:\n");
+        for (i = 0; i < argc; i++) {
+            printf("[%i]", i);
+            for (p = (unsigned char*)argv[i]; *p; p++)
+                printf(" %02X", *p);
+            printf("\n");
+        }
+    }
+
     fakeargc = argc + 3;        /* allow for "-e", my_par_pl, "--" arguments */
 #ifdef PERL_PROFILING
     fakeargc++;                 /* "-d:DProf" */
```
rebuild and install `PAR::Packer` and repack myperl.exe. What's the output when you run `myperl.exe 一 二 三 四 五 六 七 八 九 零 äö`? And for comparison, what's the output for (in the `PAR::Packer` build directory) `myldr\par.exe 一 二 三 四 五 六 七 八 九 零 äö`?

**Comment by rschupp** [comment]
I made two changes:
- No need to convert all elements of argv (from whatever CP they are encoded in) as they are not modified in `boot.c` (except for the "quote argv strings if necessary" part, temporarily commented out), use `CommandLineToArgvW(GetCommandLineW(), &argc))` to get the original command line. 
- We just have to convert `my_perl`, but I think CP_UTF8 is wrong here, it's encoded in whatever the "current" codepage is set to.

I pushed this to the "ci" branch, it passes all tests except for the ones testing Windows command line quoting rules. I'll have to reimplement them  using wchar instead of char.

Please test.
