### ISSUE TITLE
PAR-Packer lost a line of string when packing Unicode::GCString

### ISSUE THREAD

**Issue by saxyx** [rschupp/PAR-Packer#87]
If I have a perl file named aa.pl:
```
use strict;
use warnings;
use Unicode::GCString;
use utf8;

my $stringToBeMeasured = "你好，世界";
my $gcstring = Unicode::GCString->new($stringToBeMeasured);
my $columns = $gcstring->columns();

print $columns;
``` 
When I run `pp -T -M Unicode::GCString  --output aa.exe aa.pl` to generate `aa.exe`, and then execute `aa` in the cmd, I encounter the following error message:
`Can't locate object method "new" via package "Unicode::GCString" at script/aa.pl line 7.`

The first 10 lines of `GCString.pm` extracted from `aa.exe` are as follows:
```
#-*-perl-*-

package Unicode::GCString;
require 5.008;



=cut

### Pragmas:
``` 

The first 10 lines of `GCString.pm`  from the local library are:
```
#-*-perl-*-

package Unicode::GCString;
require 5.008;

=encoding utf-8

=cut

### Pragmas:
``` 

Therefore, it seems that pp loses the line `=encoding utf-8` when packaging Unicode::GCString.

### Info:

- Win11 
- Perl distribution is Strawberry Perl
- PAR Packager, version 1.062 (PAR version 1.018)

**Comment by rschupp** [comment]
`PAR::Filter::PodStrip` stumbles over 
```
=encoding utf-8

=cut
```
and removes just the `=encoding` while leaving `=cut`. Hence perl interprets everything below `=cut` as POD, i.e. no perl code.  As a quick workaround  set the environment variable  `PAR_VERBATIM=1` while packing to disable use of `PodStrip`.

**Comment by rschupp** [comment]
BTW: `pp -T -M Unicode::GCString  --output aa.exe aa.pl`
- don't use `-T`, there's no reason to ever use it
- `-M Unicode::GCString` is not necessary, it's automagically packed

**Comment by rschupp** [comment]
>  I learned the skill from https://stackoverflow.com/questions/34351026/how-to-reduce-par-folder-size-in-tmp.

That's typical stackoverflow nonsense. **Don't use `-T`.** 

Here's why: create a file named `Foo.pm` with contents
```perl
package Foo;
sub greeting { print "hello\n" };
1;
```
then run
```
$ pp -o hello.exe -T WTF -I . -E 'use Foo; Foo::greeting();'
$ .\hello.exe
hello
```
so faras expected. Now change `"hello"` to `"good bye"` in `Foo.pm` and pack again
```
$ pp -o hello.exe -T WTF -I . -E 'use Foo; Foo::greeting();'
$ .\hello.exe
hello
```
Oops! The second incarnation of `hello.exe`  reused the cache area of the first and didn't extract the new version of `Foo.pm`. If you're concerned about the stuff that accumulates in your cache area, simply blow the cache area away.

**Comment by rschupp** [comment]
> It wouldn't be a problem if you didn't specify a specific value.

That's because `-T` with an argument is simply ignored. And it doesn't help "I don't want it to decompress and take up space every time I use the aa.exe" either: if you don't regenerate an executable, decompression happens on the first run, after that the cache area is reused.
