### ISSUE TITLE
"Attempt to reload aborted" on Strawberry

### ISSUE THREAD

**Issue by VladimirAlexiev** [rschupp/PAR-Packer#88]
Hi! I'm trying to pack https://github.com/VladimirAlexiev/rdf2rml/blob/master/bin/rdfpuml.pl and all its dependencies.
I use Windows 10, Cygwin and Strawberry
`This is perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread`
I think my problems are more basic than https://groups.google.com/g/perl.par/c/KGXwXXSaz2U and that I'm doing something stupid.

This is how I pack it:
```
pp -o rdfpuml.exe -M RDF::Trine:: -M RDF::Query -M SLurp -M FindBin -a ../lib/RDF/Prefixes rdfpuml.pl
# Use of runtime loader module Module::Runtime detected.  Results of static scanning may be incomplete.
# Use of runtime loader module Module::Implementation detected.  Results of static scanning may be incomplete.
```
When I run it, I get these errors:
```
rdfpuml.exe cb-model.ttl
Attempt to reload RDF/Trine/Node/Resource.pm aborted.
Compilation failed in require at C:\tmp\par-566c6164696d697220416c6578696576\cache-2213514c7ad7aeee13764f53fb7a34812b4a3a15\inc\lib/RDF/Trine/Node.pm line 34.
BEGIN failed--compilation aborted at C:\tmp\par-566c6164696d697220416c6578696576\cache-2213514c7ad7aeee13764f53fb7a34812b4a3a15\inc\lib/RDF/Trine/Node.pm line 34.
Compilation failed in require at C:\tmp\par-566c6164696d697220416c6578696576\cache-2213514c7ad7aeee13764f53fb7a34812b4a3a15\inc\lib/RDF/Trine/Graph.pm line 82.
BEGIN failed--compilation aborted at C:\tmp\par-566c6164696d697220416c6578696576\cache-2213514c7ad7aeee13764f53fb7a34812b4a3a15\inc\lib/RDF/Trine/Graph.pm line 82.
Compilation failed in require at C:\tmp\par-566c6164696d697220416c6578696576\cache-2213514c7ad7aeee13764f53fb7a34812b4a3a15\inc\lib/RDF/Trine.pm line 115.
BEGIN failed--compilation aborted at C:\tmp\par-566c6164696d697220416c6578696576\cache-2213514c7ad7aeee13764f53fb7a34812b4a3a15\inc\lib/RDF/Trine.pm line 115.
Compilation failed in require at script/rdfpuml.pl line 14.
BEGIN failed--compilation aborted at script/rdfpuml.pl line 14.
```

Observations:
- Node.pm line 34 asks for:
```
use RDF::Trine::Node::Nil;
use RDF::Trine::Node::Blank;
use RDF::Trine::Node::Literal;
use RDF::Trine::Node::Resource; <<< HERE
use RDF::Trine::Node::Variable;
```
And all these modules are included in the PAR:
```
unzip -l rdfpuml.exe lib/RDF/Trine/Node*
Archive:  rdfpuml.exe
  Length      Date    Time    Name
---------  ---------- -----   ----
     5659  03-25-2024 11:17   lib/RDF/Trine/Node.pm
     2277  03-25-2024 11:17   lib/RDF/Trine/Node/Blank.pm
     2714  03-25-2024 11:17   lib/RDF/Trine/Node/Formula.pm
    14192  03-25-2024 11:17   lib/RDF/Trine/Node/Literal.pm
     1407  03-25-2024 11:17   lib/RDF/Trine/Node/Nil.pm
     5111  03-25-2024 11:17   lib/RDF/Trine/Node/Resource.pm
     1522  03-25-2024 11:17   lib/RDF/Trine/Node/Variable.pm
```
- I think some of these `-M` specs are redundant: eg I now notice that I forgot the double colons at the end of `RDF::Query` but a bunch of modules (and subfolders) are included in that module hierarchy
- There are 4036 files in total in the PAR 
- `RDF/Prefixes/Curie` is a local module that my script uses like this:
```
use FindBin;
use lib "$FindBin::Bin/../lib"; # Curie is my own module, not yet on CPAN
use RDF::Prefixes::Curie;
```
I noticed there are 2 copies in the archive, one would overwrite the other, but they are supposed to be equivalent (one has the POD stripped out by PAR):
```
unzip -l rdfpuml.exe|grep -i curie
     2741  03-25-2024 11:17   lib/RDF/Prefixes/Curie.pm
     5868  04-18-2022 10:38   ../lib/RDF/Prefixes/Curie.pm
```

**Comment by VladimirAlexiev** [comment]
> one would overwrite the other, but they are supposed to be equivalent (one has the POD stripped out by PAR)

I confirmed that: the only difference between  `lib/RDF/Prefixes/Curie.pm` and `../lib/RDF/Prefixes/Curie.pm` is the documentation at the end:
![image](https://github.com/rschupp/PAR-Packer/assets/536250/e0c3d95f-1237-4341-9bdd-e398b0b9b247)

**Comment by shawnlaffan** [comment]
Maybe try using the ```-I``` argument to pack from your own lib dir instead of packing the whole dir again.  
https://metacpan.org/pod/pp#-I,-lib=DIR

For example (untested):
```
pp -o rdfpuml.exe -M RDF::Trine:: -M RDF::Query -M Slurp -M FindBin -I ../lib rdfpuml.pl
```

**Comment by VladimirAlexiev** [comment]
Thanks @shawnlaffan! I'm sure this is a better way but still no cigar:
```
pp -o rdfpuml.exe -M RDF::Trine:: -M RDF::Query:: -M RDF::Prefixes::Curie -M Slurp -M FindBin -I ../lib rdfpuml.pl
rdfpuml.exe cb-model.ttl
Attempt to reload RDF/Trine/Node/Resource.pm aborted.
Compilation failed in require at C:\tmp\par-566c6164696d697220416c6578696576\cache-6857ff78efa24d3963239d019870c3e6ee4fe85e\inc\lib/RDF/Trine/Node.pm line 34.
BEGIN failed--compilation aborted at C:\tmp\par-566c6164696d697220416c6578696576\cache-6857ff78efa24d3963239d019870c3e6ee4fe85e\inc\lib/RDF/Trine/Node.pm line 34.
Compilation failed in require at C:\tmp\par-566c6164696d697220416c6578696576\cache-6857ff78efa24d3963239d019870c3e6ee4fe85e\inc\lib/RDF/Trine/Graph.pm line 82.
BEGIN failed--compilation aborted at C:\tmp\par-566c6164696d697220416c6578696576\cache-6857ff78efa24d3963239d019870c3e6ee4fe85e\inc\lib/RDF/Trine/Graph.pm line 82.
Compilation failed in require at C:\tmp\par-566c6164696d697220416c6578696576\cache-6857ff78efa24d3963239d019870c3e6ee4fe85e\inc\lib/RDF/Trine.pm line 115.
BEGIN failed--compilation aborted at C:\tmp\par-566c6164696d697220416c6578696576\cache-6857ff78efa24d3963239d019870c3e6ee4fe85e\inc\lib/RDF/Trine.pm line 115.
Compilation failed in require at script/rdfpuml.pl line 14.
BEGIN failed--compilation aborted at script/rdfpuml.pl line 14.
```

**Comment by rschupp** [comment]
See https://github.com/rschupp/PAR-Packer/issues/76#issuecomment-1691627942 for an explanation of "Attempt to reload ... aborted" and possible failure scenarios.

**Comment by VladimirAlexiev** [comment]
Trine uses `Module::Load::Conditional` to check for the presence of `Redland` library/modules that I don't use.
```perl
use Module::Load::Conditional qw[can_load];
use LWP::UserAgent;

our ($debug, @ISA, $VERSION, @EXPORT_OK);
BEGIN {
	$debug		= 0;
	$VERSION	= '1.019';
	
	require Exporter;
	@ISA		= qw(Exporter);
	@EXPORT_OK	= qw(iri blank literal variable statement store UNION_GRAPH NIL_GRAPH);
	
	unless ($ENV{RDFTRINE_NO_REDLAND}) {
		can_load( modules => {
			'RDF::Redland'					=> undef,
			'RDF::Trine::Store::Redland'	=> undef,
			'RDF::Trine::Parser::Redland'	=> undef,
		} );
```

**Comment by rschupp** [comment]
@VladimirAlexiev Can you check (with `unzip -l rdfpuml.exe`) whether `Data/Perl/Collection/Hash/MooseLike.pm` has been packed into the executable. If not, try repacking by adding `-M Data::Perl::Collection::Hash::MooseLike` to your `pp` command.

**Comment by VladimirAlexiev** [comment]
Thanks a lot, it works!!!

Is there something I can help you with to improve dependency detection?
It still gives:
```
# Use of runtime loader module Module::Runtime detected.  Results of static scanning may be incomplete.
# Use of runtime loader module Module::Implementation detected.  Results of static scanning may be incomplete.
```

**Comment by rschupp** [comment]
> Thanks a lot, it works!!!

Thanks for testing. I simply installed all required modules on linux, packed `rdfpuml.pl` and ran the excutable:
```
Can't locate Data/Perl/Collection/Hash/MooseLike.pm in @INC (you may need to install the Data::Perl::Collection::Hash::MooseLike module) (@INC contains: /tmp/par-726f646572696368/cache-3019000794a46860af7c902a93d3b3543e18ca80/inc/lib /tmp/par-726f646572696368/cache-3019000794a46860af7c902a93d3b3543e18ca80/inc CODE(0x55cfa685b698) CODE(0x55cfa685bea8)) at /tmp/par-726f646572696368/cache-3019000794a46860af7c902a93d3b3543e18ca80/inc/lib/Module/Runtime.pm line 314.
```
That is the typical error when `pp` missed some dependency of your script. Actually it's `Module::ScanDeps` job to find these dependencies. In your case module `MooX::HandlesVia` loads `Data::Perl::Collection::Hash::MooseLike` in a way that cannot be detected by "static" analysis of `MooX/HandlesVia.pm` (it's using one of those "runtime loader modules"). A simple example for this problem is `File::Spec`:
```perl
 my %module = (
              MSWin32 => 'Win32',
              os2     => 'OS2',
              VMS     => 'VMS',
              amigaos => 'AmigaOS');
my $module = $module{$^O} || 'Unix';
require "File/Spec/$module.pm";      # <--- 
```
Sometimes using `pp` option `--compile` will help in this situation. In your case `pp -c -o rdfpuml.exe -I lib rdfpuml.pl` does the trick.

I'm still puzzled about the "Attempt to reload ... abort" error message though :thinking: 

> Is there something I can help you with to improve dependency detection?

I'll add a hint to `Module::ScanDeps`: when `MooX::HandlesVia` is detected as a dependency, also add all modules "below" `Data::Perl`.
