### ISSUE TITLE
how to pass perl option `-C`

### ISSUE THREAD

**Issue by VladimirAlexiev** [rschupp/PAR-Packer#89]
Currently I run the tool I'm trying to package in https://github.com/rschupp/PAR-Packer/issues/88 like this:
```
perl -S -C rdfpuml.pl $1
```
I need the `-C` option otherwise Unicode appearing in input files get mangled.

How to pass this option to `pp`.
If I try to put it on the first script line 
```
#!perl -w -C
```
I get error
```
Too late for "-C" option at d:\GitHub\rdf2rml\bin/rdfpuml.pl line 1.
```

**Comment by jonassmedegaard** [comment]
A better place to look seems to be `man perlunicook` (or `perldoc unicook`), specifically prescription 18:
```
  ℞ 18: Make all I/O and args default to utf8
         $ perl -CSDA ...
     or
         $ export PERL_UNICODE=SDA
     or
         use open qw(:std :encoding(UTF-8));
         use Encode qw(decode);
         @ARGV = map { decode('UTF-8', $_, 1) } @ARGV;
```

Besides changing how you call the script, you also previously used `:encoding(:encoding(UTF-8)` which does strict UTF-8 parsing. You current change to using `:utf8` does relaxed parsing.

Please also note that command-line option `-CSDL` does not _always_ use UTF-8, but switches encoding based on environment variables (see prescription 16. I recommend to stay with unconditionally using UTF-8 unless you have special needs.

**Comment by rschupp** [comment]
@jonassmedegaard Thanks for the explanation. 
Closing the issue as there's nothing actionable here.
